name              'osl-php-apps'
maintainer        'Oregon State University'
maintainer_email  'chef@osuosl.org'
license           'Apache-2.0'
description       'Installs/Configures osl-php-apps'
issues_url        'https://github.com/osuosl-cookbooks/osl-php-apps/issues'
source_url        'https://github.com/osuosl-cookbooks/osl-php-apps'
chef_version      '>= 18.0'
version           '0.1.0'

supports          'almalinux', '~> 8.0'
supports          'almalinux', '~> 9.0'
supports          'almalinux', '~> 10.0'

depends          'ark'
depends          'osl-apache'
depends          'osl-php'
depends          'osl-resources'
depends          'osl-selinux'
