describe service 'httpd' do
  it { should be_enabled }
  it { should be_running }
end

describe service 'php-fpm' do
  it { should be_enabled }
  it { should be_running }
end

# The entire webroot must be owned by apache so WordPress can upgrade itself
%w(
  /var/www/blog.example.com/wordpress
  /var/www/blog.example.com/wordpress/index.php
  /var/www/blog.example.com/wordpress/wp-admin
  /var/www/blog.example.com/wordpress/wp-includes/version.php
).each do |f|
  describe file f do
    it { should exist }
    its('owner') { should eq 'apache' }
    its('group') { should eq 'apache' }
  end
end

describe file '/usr/local/bin/wp' do
  it { should exist }
  its('mode') { should cmp '0755' }
end

describe file '/var/www/blog.example.com/wordpress/wp-config.php' do
  it { should exist }
  its('content') { should match /^\# This file was generated by Chef Infra$/ }
  its('content') { should match /^define\( 'FS_METHOD', 'direct' \);$/ }
  its('content') { should_not match /AUTOMATIC_UPDATER_DISABLED/ }
end

describe apache_conf('/etc/httpd/sites-available/blog.example.com.conf') do
  its('content') { should match(/^\s+SetEnvIf X-Forwarded-Proto "https" HTTPS=on$/) }
end

# Self-managed instances are installed by Chef too, so the customer takes
# over an already-secured site
describe command('/usr/local/bin/wp core is-installed --path=/var/www/blog.example.com/wordpress --allow-root') do
  its('exit_status') { should eq 0 }
end

describe http('http://localhost/', headers: { 'host' => 'blog.example.com' }) do
  its('status') { should eq 200 }
end

describe http('http://localhost/wp-admin/install.php', headers: { 'host' => 'blog.example.com' }) do
  its('body') { should match(/already installed/i) }
end

describe http('http://localhost/wp-admin/', headers: { 'host' => 'blog.example.com' }) do
  its('status') { should eq 302 }
  its('headers.Location') { should match 'wp-login.php' }
end
