%w(php-fpm php-mysqlnd tar).each do |p|
  describe package(p) do
    it { should be_installed }
  end
end

describe service 'httpd' do
  it { should be_enabled }
  it { should be_running }
end

describe service 'mariadb' do
  it { should be_enabled }
  it { should be_running }
end

describe service 'php-fpm' do
  it { should be_enabled }
  it { should be_running }
end

describe directory '/var/www/wordpress.example.com/wordpress' do
  it { should exist }
  its('owner') { should eq 'root' }
  its('group') { should eq 'root' }
end

describe directory '/var/www/wordpress.example.com/wordpress/wp-content' do
  it { should exist }
  its('owner') { should eq 'apache' }
  its('group') { should eq 'apache' }
end

describe file '/var/www/wordpress.example.com/wordpress/wp-config.php' do
  it { should exist }
  its('owner') { should eq 'root' }
  its('group') { should eq 'root' }
  its('content') { should match /^\# This file was generated by Chef Infra$/ }
  its('content') { should match /^define\( 'AUTOMATIC_UPDATER_DISABLED', true \);$/ }
end

describe file '/var/www/wordpress.example.com/wordpress/.htaccess' do
  it { should exist }
  its('owner') { should eq 'root' }
  its('group') { should eq 'root' }
  its('content') { should match /^\# This file was generated by Chef Infra$/ }
end

describe host('localhost') do
  it { should be_reachable }
  it { should be_resolvable }
end

describe file '/usr/local/bin/wp' do
  it { should exist }
  its('mode') { should cmp '0755' }
end

describe command('/usr/local/bin/wp core version --path=/var/www/wordpress.example.com/wordpress --allow-root') do
  its('exit_status') { should eq 0 }
  its('stdout') { should match /^7\.1/ }
end

describe file('/etc/php-fpm.d/wordpress.example.com.conf') do
  it { should exist }
  its('content') { should match /^pm.max_children = 15$/ }
  its('content') { should match /^pm.start_servers = 4$/ }
  its('content') { should match /^pm.min_spare_servers = 2$/ }
  its('content') { should match /^pm.max_spare_servers = 6$/ }
end

describe http('http://localhost') do
  its('status') { should eq 200 }
  its('headers.Content-Type') { should match 'text/html' }
end

# A fresh install redirects to the WordPress installer
describe http('http://localhost/', headers: { 'host' => 'wordpress.example.com' }) do
  its('status') { should eq 302 }
  its('headers.Location') { should match 'wp-admin/install.php' }
end

describe http('http://localhost/wp-admin/install.php', headers: { 'host' => 'wordpress.example.com' }) do
  its('status') { should eq 200 }
  its('body') { should match 'WordPress' }
end

describe apache_conf('/etc/httpd/sites-available/wordpress.example.com.conf') do
  its('ServerName') { should include 'wordpress.example.com' }
  its('DocumentRoot') { should include '/var/www/wordpress.example.com/wordpress' }
  its('Options') { should include 'FollowSymLinks MultiViews' }
  its('AllowOverride') { should include 'All' }
  its('Require') { should include 'all granted' }
  its('content') { should match 'SetHandler "proxy:unix:/var/run/wordpress.example.com-fpm.sock|fcgi://localhost/"' }
  its('content') { should match(/^\s+SetEnvIf X-Forwarded-Proto "https" HTTPS=on$/) }
end

describe mysql_session('wordpress_owner', 'wordpress_password').query('SHOW databases') do
  its('stdout') { should match 'wordpress' }
end
