
%w(php-mysqlnd tar).each do |p|
  describe package(p) do
    it { should be_installed }
  end
end

describe service 'httpd' do
  it { should be_enabled }
  it { should be_running }
end

describe service 'mariadb' do
  it { should be_enabled }
  it { should be_running }
end

describe service 'php-fpm' do
  it { should be_enabled }
  it { should be_running }
end

describe directory '/var/www/yourls.example.com/yourls' do
  it { should exist }
  its('owner') { should eq 'root' }
  its('group') { should eq 'root' }
end

describe file '/var/www/yourls.example.com/yourls/user/config.php' do
  it { should exist }
  its('owner') { should eq 'root' }
  its('group') { should eq 'root' }
  its('content') { should match /^\# This file was generated by Chef Infra$/ }
end

describe file '/var/www/yourls.example.com/yourls/.htaccess' do
  it { should exist }
  its('owner') { should eq 'root' }
  its('group') { should eq 'root' }
  its('content') { should match /^\# This file was generated by Chef Infra$/ }
end

describe host('localhost') do
  it { should be_reachable }
  it { should be_resolvable }
end

describe file('/etc/php-fpm.d/yourls.example.com.conf') do
  it { should exist }
  its('content') { should match /^pm.max_children = 43$/ }
  its('content') { should match /^pm.start_servers = 10$/ }
  its('content') { should match /^pm.min_spare_servers = 10$/ }
  its('content') { should match /^pm.max_spare_servers = 32$/ }
end

describe http('http://localhost') do
  its('status') { should eq 200 }
  its('headers.Content-Type') { should match 'text/html' }
end

describe http('http://localhost/admin/index.php', headers: { 'host' => 'yourls.example.com' }) do
  its('status') { should eq 200 }
end

describe apache_conf('/etc/httpd/sites-available/yourls.example.com.conf') do
  its('ServerName') { should include 'yourls.example.com' }
  its('DocumentRoot') { should include '/var/www/yourls.example.com/yourls' }
  its('Options') { should include 'FollowSymLinks MultiViews' }
  its('AllowOverride') { should include 'All' }
  its('Require') { should include 'all granted' }
  its('content') { should match "SetHandler \"proxy:unix:/var/run/yourls.example.com-fpm.sock|fcgi://localhost/\"" }
end

describe mysql_session('yourls_owner','yourls_password').query('SHOW databases') do 
  its('stdout') { should match 'yourls' }
end